### ISSUE TITLE
containerd 1.7.28-0: illegal instruction on RPI Zero W (ARMv6)

### ISSUE THREAD

**Issue by AloisKlingler** [docker/containerd-packaging#428]
hello,

not sure if this is the correct place for this issue...

it looks like the current release of containerd (1.7.28-0~raspbian.12~bookworm) is not compatible with ARMv6 any more.
I am using an RPI zero W (NOT RPI zero W 2 which has another CPU architecture!), containerd gives there "Illegal instruction" on starting manually, systemd job fails with "(core dumped)" 

I downgraded to containerd.io (1.7.27-1)

and containerd looks good again.

as "docker --help" still showed:
Invalid Plugins:
  buildx      failed to fetch metadata: signal: illegal instruction
  compose     failed to fetch metadata: signal: illegal instruction
  model       failed to fetch metadata: signal: illegal instruction

I had to downgrade more packages and currently running
containerd.io (1.7.25-1)
docker-buildx-plugin (0.21.1-1~raspbian.12~bookworm
docker-ce-cli (5:28.0.1-1~raspbian.12~bookworm)
docker-ce (5:28.0.1-1~raspbian.12~bookworm)
docker-compose-plugin (2.33.1-1~raspbian.12~bookworm)

and now at least  docker compose pull && docker compose up -d is working again.

still I have
  model       failed to fetch metadata: signal: illegal instruction

but as I do not use this, my docker installation is working again.

maybe somebody has hints or can tell me how / what to do to have the latest versions running correct?

thanks!

cat /proc/cpuinfo 
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 1423.06
Features        : half thumb fastmult vfp edsp java tls 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2835
Revision        : 9000c1
Serial          : XXXXXXXXXXXXXXXX
Model           : Raspberry Pi Zero W Rev 1.1

uname -a
6.12.47+rpt-rpi-v6 #1 Raspbian 1:6.12.47-1+rpt1~bookworm (2025-09-16) armv6l GNU/Linux

**Comment by vvoland** [comment]
Thanks for the report, we deployed a new revision of containerd `containerd.io_1.7.28-2~raspbian.11~bullseye_armhf.deb` - please check if it fixes the issue

**Comment by AloisKlingler** [comment]
@vvoland partially working now. seems that docker-compose package does still not fit.
containerd starts again correctly

installed packages:
```
dpkg -l | grep docker
ii  docker-buildx-plugin                 0.29.1-1~raspbian.12~bookworm            armhf        Docker Buildx plugin extends build capabilities with BuildKit.
ii  docker-ce                            5:28.5.0-1~raspbian.12~bookworm          armhf        Docker: the open-source application container engine
ii  docker-ce-cli                        5:28.5.0-1~raspbian.12~bookworm          armhf        Docker CLI: the open-source application container engine
ii  docker-ce-rootless-extras            5:28.5.0-1~raspbian.12~bookworm          armhf        Rootless support for Docker.
ii  docker-compose-plugin                2.39.4-0~raspbian.12~bookworm            armhf        Docker Compose (V2) plugin for the Docker CLI.
ii  docker-model-plugin                  0.1.40-0~raspbian.12~bookworm            armhf        Docker Model Runner plugin for the Docker CLI.
```

but:
```
Invalid Plugins:
  compose     failed to fetch metadata: signal: illegal instruction
  model       failed to fetch metadata: signal: illegal instruction
```

downgrade to:
docker-compose-plugin=2.33.1-1~raspbian.12~bookworm
docker-model-plugin=0.1.39-1~raspbian.12~bookworm

removes the error and makes "docker compose pull" working again.

**Comment by vvoland** [comment]
Thanks! Yes previously I only rebuilt the containerd package.

Just updated compose and model to the latest versions and those should be fine now.

**Comment by AloisKlingler** [comment]
👍works now.
docker-compose-plugin (2.40.0-1~raspbian.12~bookworm)
docker-model-plugin (0.1.42-1~raspbian.12~bookworm)

**Comment by vvoland** [comment]
Thanks for testing!

I'll close this issue as everything should now work correctly, but feel free to ping me/open a new ticket in case the issue persists!
